sbt "run ../dags/avianflu_large.dag" > ../dags/avianflu_large.dag.ampl
sbt "run ../dags/cptest.dag" > ../dags/cptest.dag.ampl
sbt "run ../dags/CyberShake_100.dag" > ../dags/CyberShake_100.dag.ampl
sbt "run ../dags/CyberShake_1000.dag" > ../dags/CyberShake_1000.dag.ampl
sbt "run ../dags/CyberShake_30.dag" > ../dags/CyberShake_30.dag.ampl
sbt "run ../dags/CyberShake_50.dag" > ../dags/CyberShake_50.dag.ampl
sbt "run ../dags/cybershake_small.dag" > ../dags/cybershake_small.dag.ampl
sbt "run ../dags/Epigenomics_997.dag" > ../dags/Epigenomics_997.dag.ampl
sbt "run ../dags/GENOME.n.1000.0.dag" > ../dags/GENOME.n.1000.0.dag.ampl
sbt "run ../dags/Inspiral_1000.dag" > ../dags/Inspiral_1000.dag.ampl
sbt "run ../dags/Montage_1000.dag" > ../dags/Montage_1000.dag.ampl
sbt "run ../dags/Montage_25.dag" > ../dags/Montage_25.dag.ampl
sbt "run ../dags/psload_large.dag" > ../dags/psload_large.dag.ampl
sbt "run ../dags/psload_medium.dag" > ../dags/psload_medium.dag.ampl
sbt "run ../dags/psmerge_large.dag" > ../dags/psmerge_large.dag.ampl
sbt "run ../dags/psmerge_small.dag" > ../dags/psmerge_small.dag.ampl
sbt "run ../dags/Sipht_1000.dag" > ../dags/Sipht_1000.dag.ampl
sbt "run ../dags/test.dag" > ../dags/test.dag.ampl
sbt "run ../dags/topotest.dag" > ../dags/topotest.dag.ampl
